#include <stdlib.h>

#include "Constants/Constants.h"


const int RAND_MAX_HALF                  = RAND_MAX / 2;

const FLOAT_TYPE WINDOW_SIDE_LENGTH_HALF = WINDOW_SIDE_LENGTH / 2;

const FLOAT_TYPE PLOT_AREA_SIDE_LENGTH   = WINDOW_SIDE_LENGTH - 2 * PLOT_AREA_INSET;

const FLOAT_TYPE
    AXES_MAX_POSITION = WINDOW_SIDE_LENGTH - PLOT_AREA_INSET,
    AXES_MIN_POSITION = PLOT_AREA_INSET;

const SDL_Colour
    FOREGROUND_COLOUR = { 255, 255, 255, 255 },
    BACKGROUND_COLOUR = { 0, 0, 0, 255 };

const int
    VECTOR_COUNT = VECTOR_ROW_COUNT * VECTOR_COLUMN_COUNT;

const FLOAT_TYPE
    VECTOR_LENGTH_HALF = VECTOR_LENGTH / 2;

const FLOAT_TYPE PARTICLE_SIZE_HALF = PARTICLE_SIZE / 2;